apiVersion: extensions/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: search-app
  labels:
    app: search-app
    name: search-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-app
      name: search-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: search-app
        name: search-app
    spec:
      containers:
        - name: search-app
          imagePullPolicy: Always
          image: gcr.io/obu-fyp-yuhao/search-app:1.0.0
          command: ["/bin/bash", "-c", "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
          ports:
            - containerPort: 80
          env:
            - name: API_HOST
              value: "search-api-lb"
            - name: API_PORT
              value: "8080"

---
kind: Service
apiVersion: v1
metadata:
  name: search-app-lb
spec:
  type: LoadBalancer
  selector:
    app: search-app
    name: search-app
  ports:
  - name: search-app-port
    protocol: TCP
    port: 80
    targetPort: 80